# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: true
permalink: /:categories/:title/
exclude: [ 'node_modules' ]
# Setup
title:            Elijah Manor
tagline:          'Front-End Dev Tips, Tricks, and Tools'
descriptions:     'Front-End Dev Tips, Tricks, and Tools'
url:              http://elijahmanor.com
baseurl:          ""

author:
  name:           'Elijah Manor'
  url:            https://twitter.com/elijahmanor

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/elijahmanor/elijahmanor.github.com
