markdown: kramdown
kramdown:
  syntax_highlighter: rouge

permalink: /:categories/:title/
exclude: ['node_modules']
keep_files: ['talks']

title: Manorisms
title_image:
tagline: 'Front-End Dev Tips, Tricks, and Tools'
description: 'Front-End Dev Tips, Tricks, and Tools'
url: https://elijahmanor.com

author:
  name: 'Manorisms'
  url: https://twitter.com/elijahmanor

paginate: 5

version: 2.1.0
github:
  repo: https://github.com/elijahmanor/elijahmanor.github.com
